resources:
  repositories:
    - repository: owaspzapui
      type: github
      endpoint: UKHO
      name: UKHO/owasp-zap-ui-scan
      ref: refs/heads/master

jobs:
- template: owasp-zap-ui-scan-template.yml@owaspzapui
  parameters:
    url: $(ApplicationUrl)
