resources:
  repositories:
    - repository: owaspzapapi
      type: github
      endpoint: UKHO
      name: UKHO/owasp-zap-scan
      ref: refs/heads/master

jobs:
- template: owasp-zap-api-scan-template.yml@owaspzapapi
  parameters:
    url: $(SwaggerDefUrl)
    publishAsTestResults: true
